channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.1.1
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.15.3
name: mlflow-env
